# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mywebsite.wsgi

beta_settings:
    cloud_sql_instances: website-260119:europe-west1:website-posgre-instance

runtime_config:
  python_version: 3
# [END runtime]